theme: Didier Iradukunda
title: Machine Learning Engineer
description: 
I'm Didier Iradukunda. A 2022 graduate from Carnegie Mellon University, Msc. Electrical & Computer Engineering. I majored in Applied Machine Learning and have more interests in Deep Learning and Computer Vision Applications.

I am currently working as A Graduate Teaching Assistant at Carnegie Mellon University. I have practical experience in Data exploration; Visualization, Big Data, Building Machine Learning Models and Communicating insights from the Data. Have over two years of experience in Telecommunication and Energy Systems. 

Broadly, I aspire to leverage data and assist in improving people’s lives through the increased access to sustainable and modern solutions.
